---

- name: disable force unload registry - {{ task_state | default('present') }}
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: DisableForceUnload
    data: 1
    type: dword
    state: "{{ task_state | default('present') }}"
  register: disable_force_unload_registry