---

- name: update over multiple reboots
  block:
    - block:
        - name: set reject list
          set_fact:
            _reject_list: "{{ (win_update_reject_list | default([])) + (failed_kb | default([])) }}"
          when: (win_update_reject_list | length) or (failed_kb | length)

        - name: install all windows updates
          win_updates:
            category_names: "{{ win_update_category_names }}"
            reject_list: "{{ _reject_list | default(omit) }}"
            accept_list: "{{ win_update_accept_list | default(omit) }}"
            reboot: yes
          register: installed_updates

      rescue:
        - name: reboot the system to recover from a failed update
          win_reboot:
            reboot_timeout: 7200

        - name: set failed KB to skip
          set_fact:
            failed_kb: "{{ failed_kb|default([]) + [installed_updates.msg | regex_replace('^.*\\((KB.*)\\).*','\\1')] }}"
          when:
            - installed_updates.msg is defined
            - ('Failed' in installed_updates.msg)
            - ('KB' in installed_updates.msg)

        - name: fail to retry
          fail:
            msg: "There are failed updates: {{ failed_kb | join(' ') }}"
          when:
            - failed_kb is defined
            - failed_kb | length > 0

    - name: wait for system to be responsive after update
      wait_for_connection:
        delay: 60
        sleep: 10
        timeout: 600

    - name: work on any skipped KB
      win_updates:
        category_names: "{{ win_update_category_names }}"
        reject_list: "{{ win_update_reject_list | default(omit) }}"
        accept_list: "{{ failed_kb | default(omit) }}"
        reboot: yes
      register: installed_updates_retry_skipped
      when:
        - failed_kb is defined
        - failed_kb | length > 0

    - name: check for missing updates
      win_updates:
        category_names: "{{ win_update_category_names }}"
        reject_list: "{{ win_update_reject_list | default(omit) }}"
        state: searched
      register: missing_updates

    - debug:
        msg: |
          {{ inventory_hostname }} has {{ missing_updates.found_update_count }} updates still missing.
          {% for update in updates %}
            - {{ update.title }}
          {% endfor %}
      vars:
        updates: "{{ (missing_updates.updates.values() | list) if (missing_updates.updates is mapping) else (missing_updates.updates) }}"
      when: missing_updates.updates is defined

    - name: still more updates - need to retry
      fail:
        msg: >
          '{{ inventory_hostname }} has {{ missing_updates.found_update_count }} updates still missing.
          {{ (update_retry_limit | int) - (update_retry_count | int) }} more retries left'
      when:
        - missing_updates.found_update_count > 0
        - ((update_retry_limit | int) - (update_retry_count | int) > 0)

  rescue:
    - name: set update count
      set_fact:
        update_retry_count: '{{ update_retry_count | default(0) | int + 1 }}'

    - debug:
        msg: "Still more updates ({{ current_update_count }}) remaining - retrying... ({{ update_retry_count }}/{{ update_retry_limit }})"
      vars:
        current_update_count: "{{ missing_updates.found_update_count | default(installed_updates.found_update_count) | default('-') }}"

    - name: ensure system is reachable
      wait_for_connection:
        sleep: 10
        timeout: 600

    - include_tasks: updates-with-retry.yml
      when: ((update_retry_limit | int) - (update_retry_count | int) > 0)